# Generated by Django 3.2.7 on 2021-11-21 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='car_pics')),
                ('speed', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('temperature', models.FloatField()),
                ('fuel_level', models.IntegerField()),
                ('Engine_status', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Invalid engine status code', regex='^[PCBU]{1}[0123]{1}[1-8]{1}[0-9]{2}$')])),
            ],
        ),
    ]
